<?php

declare(strict_types=1);

return [
    /*
    |--------------------------------------------------------------------------
    | Default Payment Gateway
    |--------------------------------------------------------------------------
    |
    | This option controls the default payment gateway that will be used when
    | creating new subscriptions or charges. You may set this to any of the
    | gateways defined in the "gateways" array below.
    |
    */

    'default' => env('CASHIER_GATEWAY', 'stripe'),

    /*
    |--------------------------------------------------------------------------
    | Payment Gateways
    |--------------------------------------------------------------------------
    |
    | Here you may configure all of the payment gateways for your application.
    | Each gateway can be configured with its own credentials and settings.
    | Gateways will only be loaded if their dependencies are installed.
    |
    | Supported gateways: "stripe", "chip"
    |
    */

    'gateways' => [
        'stripe' => [
            'driver' => 'stripe',
            'key' => env('STRIPE_KEY'),
            'secret' => env('STRIPE_SECRET'),
            'webhook_secret' => env('STRIPE_WEBHOOK_SECRET'),
            'currency' => env('CASHIER_CURRENCY', 'USD'),
            'currency_locale' => env('CASHIER_CURRENCY_LOCALE', 'en_US'),
        ],

        'chip' => [
            'driver' => 'chip',
            'brand_id' => env('CHIP_BRAND_ID'),
            'api_key' => env('CHIP_API_KEY'),
            'webhook_key' => env('CHIP_WEBHOOK_KEY'),
            'currency' => env('CASHIER_CURRENCY', 'MYR'),
            'currency_locale' => env('CASHIER_CURRENCY_LOCALE', 'ms_MY'),
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Customer Model
    |--------------------------------------------------------------------------
    |
    | Configure the customer model class used by Cashier.
    |
    */

<<<<<<< Updated upstream
<<<<<<< Updated upstream
    'subscription_gateways' => [
        // 'premium' => 'stripe',
        // 'local' => 'chip',
    ],

    /*
    |--------------------------------------------------------------------------
    | Models
    |--------------------------------------------------------------------------
    |
    | Configure the model classes used by Cashier. You may extend these models
    | in your application if you need to customize their behavior.
    |
    */

    'models' => [
        'customer' => env('CASHIER_MODEL', 'App\\Models\\User'),
        'subscription' => AIArmada\Cashier\Models\Subscription::class,
        'subscription_item' => AIArmada\Cashier\Models\SubscriptionItem::class,
    ],
=======
    'customer_model' => env('CASHIER_MODEL', 'App\\Models\\User'),
>>>>>>> Stashed changes
=======
    'customer_model' => env('CASHIER_MODEL', 'App\\Models\\User'),
>>>>>>> Stashed changes

    /*
    |--------------------------------------------------------------------------
    | Cashier Path
    |--------------------------------------------------------------------------
    |
    | This is the base URI path where Cashier's views, such as the payment
    | confirmation page, will be available from. You may change this path
    | to anything you like.
    |
    */

    'path' => env('CASHIER_PATH', 'cashier'),

    /*
    |--------------------------------------------------------------------------
    | Webhook Routes
    |--------------------------------------------------------------------------
    |
    | Configure the webhook routes for each gateway. These paths will be
    | prefixed with the Cashier path configured above.
    |
    */

    'webhooks' => [
        'stripe' => 'webhook/stripe',
        'chip' => 'webhook/chip',
    ],

    /*
    |--------------------------------------------------------------------------
    | Invoice Settings
    |--------------------------------------------------------------------------
    |
    | Configure the default settings for invoices generated by Cashier.
    |
    */

    'invoices' => [
<<<<<<< Updated upstream
<<<<<<< Updated upstream
        'renderer' => AIArmada\Cashier\Invoices\DompdfInvoiceRenderer::class,
=======
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes
        'paper' => 'letter',
        'logo' => null,
        'vendor' => [
            'name' => env('APP_NAME', 'Your Company'),
            'address' => null,
            'phone' => null,
            'email' => null,
            'url' => env('APP_URL'),
            'vat' => null,
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Subscription Behavior
    |--------------------------------------------------------------------------
    |
    | Configure the default behavior for subscriptions across all gateways.
    |
    */

    'subscriptions' => [
        // Automatically mark past due subscriptions as inactive
        'deactivate_past_due' => true,

        // Automatically mark incomplete subscriptions as inactive
        'deactivate_incomplete' => true,

        // Days to allow for payment retry before marking as past due
        'grace_period_days' => 3,
    ],
];
