# Testing Guidelines
- **Goal**: ELIMINATE BUGS.
- **Refs**: Filament Testing Docs (Resources, Tables, Schemas).
- **Exec**:
- **Single**: `./vendor/bin/pest path/to/Test.php`.
- **Dir**: `./vendor/bin/pest path/to/dir`.
- **Full**: `./vendor/bin/pest --parallel ...` (Final only).
- **Coverage**:
- Don't run full if `0% files > 10%`.
- Command: `./vendor/bin/pest --coverage ...`.
- Targets: Core ≥85%, Filament ≥70%, Support ≥80%.
- **Output**: ALWAYS pipe: `2>&1 | tee /tmp/out.txt`.